### ISSUE TITLE
Blocked results differ from Ublock origin?

### ISSUE THREAD

**Issue by dud3** [ghostery/adblocker#1873]
Tried comparing blocked requests of this library to ublock origin chrome plugin got different results.

URL: http://businessinsider.com

I used the events of the following example to collect blocked request: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer-example/index.ts but only got 6 blocked requests where ublock origin chrome plugin found 22.

Perhaps there is another way of collecting blocked requests?

**Comment by dud3** [comment]
cc @remusao

**Comment by remusao** [comment]
Hey @dud3,

Sorry, somehow I missed the notifications for this issue. I would need to check to understand why uBO and the library yield different results. Do you maybe have a list of requests for both? Maybe a diff of which requests blocked by uBO were not blocked by `@cliqz/adblocker` would help to get started,

Best,

**Comment by remusao** [comment]
Closing this. Feel free to re-open if this is still an issue.
