### ISSUE TITLE
Default lists loaded?

### ISSUE THREAD

**Issue by vprelovac** [ghostery/adblocker#2426]
Can you specify what are default lists loaded (and location of this configuration)? Thanks!

**Comment by remusao** [comment]
Hi @vprelovac,

Thanks for reaching out. You can find the lists used in the different presets here: [ads only](https://github.com/ghostery/adblocker/blob/ef0421ad4dbe3bda9b4e54ae6f6502a025c0dfff/packages/adblocker/src/fetch.ts#L55), [ads + tracking](https://github.com/ghostery/adblocker/blob/ef0421ad4dbe3bda9b4e54ae6f6502a025c0dfff/packages/adblocker/src/fetch.ts#L68), [ads + tracking + annoyances](https://github.com/ghostery/adblocker/blob/ef0421ad4dbe3bda9b4e54ae6f6502a025c0dfff/packages/adblocker/src/fetch.ts#L74).

These are just the built-in rules hosted mirrored on the GitHub repository for convenience ([this script](https://github.com/ghostery/adblocker/blob/master/packages/adblocker/assets/update.js) is used for updates) but you can of course specify your own (e.g. if you have extra lists to include, or want to serve them from a CDN), by initializing the content blocker using its [fromLists](https://github.com/ghostery/adblocker/blob/ef0421ad4dbe3bda9b4e54ae6f6502a025c0dfff/packages/adblocker/src/engine/engine.ts#L124) static method. You can find [an example](https://github.com/ghostery/adblocker/tree/master/packages/adblocker#usage) in the README.md.

Best,
Rémi

**Comment by remusao** [comment]
> > You can find the lists used in the different presets here: [ads only](https://github.com/ghostery/adblocker/blob/ef0421ad4dbe3bda9b4e54ae6f6502a025c0dfff/packages/adblocker/src/fetch.ts#L55), [ads + tracking](https://github.com/ghostery/adblocker/blob/ef0421ad4dbe3bda9b4e54ae6f6502a025c0dfff/packages/adblocker/src/fetch.ts#L68), [ads + tracking + annoyances](https://github.com/ghostery/adblocker/blob/ef0421ad4dbe3bda9b4e54ae6f6502a025c0dfff/packages/adblocker/src/fetch.ts#L74).
> 
> Thanks, but which one of these is set as default when adblocker is initialized with no params?
> 
> And to check, If fromLists is used no default lists are used, just what is passed to it?

Correct. It depends how you initialize the adblocker. In principle there is no default, it's always explicit (e.g. `.fromPrebuiltAdsOnly()`, `.fromPrebuiltAdsAndTracking()`, `fromLists()`, etc.)

**Comment by vprelovac** [comment]
This is great. Do you think you can add it to default documentation. There is a lot of gold in issues (and you are handling questions in an excellent way) - some of that should find its way back to documentation.

**Comment by remusao** [comment]
I'd be happy to but I have relatively little bandwidth lately. The documentation has been needing a fresh layer of paint for a long time. Any suggestions you might have in terms of what's missing, what you would expect to see first, etc.

Cc @chrmod
