### ISSUE TITLE
Blocking images/css/fonts without using the blocking approach, request.abort instead

### ISSUE THREAD

**Issue by xecgr** [ghostery/adblocker#2434]
Hi, I need to abort images requests in order to speed up the page loading time.
I would like to know if I can skip using the blocking feature like you pointed in other issues (for performance purposes)
```
   blocker.updateFromDiff({
      added: [
          '.jpg|$image',
          '.gif|$image',
       ],
   });
```
I've followed steps listed in this #[comment](https://github.com/ghostery/adblocker/issues/493#issuecomment-585873954) but I'm still getting `UnhandledPromiseRejectionWarning: Error: Request is already handled!` error. What I am doing wrong?

My code below:
```

const puppeteer = require('puppeteer');
const { PuppeteerBlocker,fromPuppeteerDetails } = require('@cliqz/adblocker-puppeteer');
const fetch = require('node-fetch');

const EXTRA_BLOCKER_LISTS = [
  'https://easylist.to/easylist/easylist.txt',                                                //EasyList
  'https://easylist.to/easylist/easyprivacy.txt',                                             //EasyPrivacy 
  'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext',  //Peter Lowe’s Ad and tracking server list 
];

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    // devtools: true,
    ignoreHTTPSErrors: true,
    args: [
      "--no-sandbox", 
      "--disable-setuid-sandbox", 
      "--unhandled-rejections=strict"
    ], 
  })
  const page    = await browser.newPage();
  const blocker = await PuppeteerBlocker.fromLists(fetch, EXTRA_BLOCKER_LISTS).then((blocker) => {
    page.on('domcontentloaded', (frame) => blocker.onFrameNavigated(page.mainFrame()));
    page.on('frameattached', (frame) => blocker.onFrameNavigated(frame));
    //approach 1, got from https://github.com/ghostery/adblocker/issues/493#issuecomment-585873954
    // page.on('request', (request) => {
    //   const { redirect, match } = blocker.match(fromPuppeteerDetails(request));
    //   if (redirect !== undefined) {
    //     request.respond({
    //       body: redirect.body,
    //       contentType: redirect.contentType,
    //     });
    //   } else if (match === true) {
    //     request.abort('blockedbyclient');
    //   } else {
    //     request.continue();
    //   }
    // });
    //approach 2, focused on avoiding load static resources in order to speed up page loading
    page.on('request', (req) => {
      if(req.resourceType() == 'stylesheet' || req.resourceType() == 'font' || req.resourceType() == 'image'){
        req.abort();
      }
      else {
        req.continue();
      }
    });
    return blocker
  });
  let url = "https://foxnews.com/"
  await blocker.enableBlockingInPage(page)
  res = await page.goto(url)
  await browser.close();
})();
```

Both approaches, 1 and 2, are failing with the same error. I think second approach is simpler, but I'm open to listen any solutions coming from your end.
Thanks for your time!

**Comment by remusao** [comment]
Hi @xecgr,

Thanks for reaching out. If you do not need to manipulate the requests from Puppeteer explicitly, I would do something like the following and let the blocker do all the work:

```javascript
const puppeteer = require("puppeteer");
const {
  PuppeteerBlocker,
  fromPuppeteerDetails,
} = require("@cliqz/adblocker-puppeteer");
const fetch = require("node-fetch");

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    // devtools: true,
    ignoreHTTPSErrors: true,
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--unhandled-rejections=strict",
    ],
  });
  const page = await browser.newPage();

  // Create initial instance of blocker from lists
  const blocker = await PuppeteerBlocker.fromPrebuiltAdsAndTracking(fetch);

  // Here we update the adblocker to also block specific resources
  blocker.blockImages().blockFonts().blockStyles();

  // Start blocking in page
  await blocker.enableBlockingInPage(page);

  let url = "https://foxnews.com/";
  res = await page.goto(url);
  await browser.close();
})();
```

You can enable the adblocker given the default lists for ads and tracking (to block as much requests as possible), and then before starting blocking you can update the blocker by adding blocking for images, fonts and styles using the methods `blockImages()`, etc.

Also note that `enableBlockingInPage` is async and needs to be awaited.

I hope this helps,
Rémi

**Comment by xecgr** [comment]
My production script is a little bit more complicated because it has defined a callback for `request-blocked` event. If I add `blockImages()` every single image will trigger the blocking event. 
Are there any way to `abort` the request instead of `blocking` it? If it isn't any, I will be forced to double check if the blocked url testing if it is an image or not.
Proceeding like this, I'll discard some tracking items like facebook pixel and other approaches that hides its activity using an image link. Are there any workaround to deal with this use case?

Thank you again for your effort and your help!

**Comment by remusao** [comment]
> If I add blockImages() every single image will trigger the blocking event.

That is true. If this is important maybe it is possible to filter the events that you want from the listener? It should not be too hard to ignore the ones from filter created by `blockImages()`.

Otherwise, if you need to register your own listeners alongside the adblocker, you will have to use the cooperative mode for Puppeteer: https://github.com/puppeteer/puppeteer/blob/v10.2.0/docs/api.md#upgrading-to-cooperative-mode-for-package-maintainers

It can customize it using the method `setRequestInterceptionPriority(priority)` of the blocker instance. It is not documented but it should work. @akornatskyy worked on adding this feature so he might have a bit more insights regarding how it should integrate with your own code base.

> Proceeding like this, I'll discard some tracking items like facebook pixel and other approaches that hides its activity using an image link. Are there any workaround to deal with this use case?

Can you explain what you meant here? I am not sure what "discard some tracking items like facebook pixel" mean. Do I understand correctly that you do not want to block them?

**Comment by xecgr** [comment]
> Proceeding like this, I'll discard some tracking items like facebook pixel and other approaches that hides its activity using an image link. Are there any workaround to deal with this use case?

If I blocked all images, the attached block-url will be shadowed as an image instead of a real blocking due to a rule.
![Screen Shot 2022-02-08 at 19 57 51](https://user-images.githubusercontent.com/2619966/153058400-af788cda-1a5b-49e1-95ae-0a4b6c11796c.png)


My intention is blockings all list-matches with the better performance (not fetching images/css/etc) without losing real matches with a wider rule like `blockImages()`
Does it makes sense?

**Comment by remusao** [comment]
Does it mean that you need to know if the same request would have been blocked by a rule from a list?

In any case, if you need to perform blocking from the adblocker as well as your own logic, I think using cooperative request handling is the way to go.

**Comment by xecgr** [comment]
> Does it mean that you need to know if the same request would have been blocked by a rule from a list?
Yes, it does! This will be super useful!

> In any case, if you need to perform blocking from the adblocker as well as your own logic, I think using cooperative request handling is the way to go.
Ok, I'll have a look to puppeteer api.

Thank you very much!

**Comment by remusao** [comment]
These might be useful as well:

* https://github.com/ghostery/adblocker/pull/2281
* https://github.com/ghostery/adblocker/pull/2343

They contain information about using cooperative mode with the adblocker.

**Comment by xecgr** [comment]
I'll follow your advice. Thanks again!
