### ISSUE TITLE
AdBlocker blocks entire body

### ISSUE THREAD

**Issue by bennyborn** [ghostery/adblocker#2493]
Hi there, hope this is the right repository since your support stated my problem might be related to your ad blocking feature.

When visiting any of the following pages the entire body gets set to `display: none`

- https://www.rheinhessische.de/
- https://www.numero2.de/
- https://www.hunkler.de/
- https://www.obstbau.org/
- https://www.winzervereindeidesheim.de/
- https://contao-marketingsuite.com/

This is due to a list of CSS-selectors that is used to block certain elements. One of these selectors is `.cookie-bar-visible` which applies to the `body` of each aforementioned page if the Cookie-Consent is shown.

The Cookie-Consent is part of an extension for the CMS Contao. Being the author of this extension I can tell you that there are at least 10.000 more potential sites that are blocked this way so a general solution to those "lax" selectors would be needed.

**Comment by remusao** [comment]
Hi @bennyborn,

Thanks for reaching out. Could you please provide some information as to how you are currently using the library and maybe some code that I could use to reproduce the issue? Are you using it as part of puppeteer, electron, webextension?

Best,

**Comment by bennyborn** [comment]
Hi @remusao,

I'm not using your library at all. 
Some of our users made us aware of the problem while using the Ghostery Browser Extension.
As I said, not sure of this is the right repository but the Ghostery Support only adviced to open up an issue on GH.

**Comment by remusao** [comment]
I see, usually these issues are best reported in the following repository: https://github.com/ghostery/ghostery-extension

Cc @chrmod

**Comment by bennyborn** [comment]
Thanks for the guidance!
