### ISSUE TITLE
How does this adblocker work?

### ISSUE THREAD

**Issue by sgebr01** [ghostery/adblocker#2548]
I am wondering how this ad-blocker works to block ads from filter lists. What npm package or method is being used to block a domain once it has been identified as one that needs to be blocked? Are you reading all traffic that goes through a page to determine if it needs to be left alone or blocked?

**Comment by remusao** [comment]
At a high level, yes, the adblocker is inspecting all network traffic (each network request) before it is being sent, and tries to match it against our database of patterns. The way we intercept the network traffic is different depending on the platform (it is not the same in a browser extension, puppeteer, electron, or react native for example).

For a more detailed introduction about how adblockers work I can recommend this reading: https://0x65.dev/blog/2019-12-20/not-all-adblockers-are-born-equal.html

**Comment by sgebr01** [comment]
OK, thanks for the response, I am wondering what npm package is used to view and block requests in Electron.

**Comment by remusao** [comment]
No particular package, we use Electron event listeners directly. You can find the code here: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L83
