### ISSUE TITLE
Use of adblocker-puppeteer cause chromium to crash

### ISSUE THREAD

**Issue by akornatskyy** [ghostery/adblocker#2626]
Here is the error that cause it to crash (linux only):

```
FATAL:mime_sniffing_url_loader.cc(134)] Check failed: net::OK != status.error_code (0 vs. 0)
```

**Comment by akornatskyy** [comment]
I think it has something to do with `request.abort('blockedbyclient', 0);`, when this set to a number higher than in adblocker it works. crash happens when it is the same...

**Comment by remusao** [comment]
That sounds like a potential bug in puppeteer? Could you maybe open an issue upstream? I don't think it should be able to crash the process by using the request interception.
