### ISSUE TITLE
How would one use this in a Nativefied app?

### ISSUE THREAD

**Issue by SpektacleFR** [ghostery/adblocker#2698]
There's a package called [Nativefier](https://github.com/nativefier/nativefier) which wraps a website with Electron (I think it uses electron).  How would one go about using this AdBlocker on one of those apps?  You can access all of the JS scripts easily, but I don't know where I would put the code snippet to start the blocker.

**Comment by Zany-Zachary1** [comment]
@remusao Thanks for pointing me there.  I will definitely ask there, but I'm still a beginner with all of this, so we'll see.
