### ISSUE TITLE
Library API's

### ISSUE THREAD

**Issue by grinono** [ghostery/adblocker#2932]
Is there any documentation on how to interact with the library, like getting the number of ads blocked, number of trackers blocked, start/stopping the blocker.

**Comment by remusao** [comment]
Hi @grinono,

The documentation is unfortunately lacking... you can find some of the APIs here: https://github.com/ghostery/adblocker/tree/master/packages/adblocker#adblocker

To know how many requests are blocked (and also other kinds of events), you can check this example: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-webextension-example/background.ts#L65

The types can be helpful here as well. You can find the list of events: https://github.com/ghostery/adblocker/blob/master/packages/adblocker/src/engine/engine.ts#L85

Any recommendation on how to improve the documentation? It's something we could definitely use some help with/work on.

I hope that helps,
