### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by im-ashar** [ghostery/adblocker#3157]
Hi,
**I have not very much knowledge of javascript**

I am embedding an iframe in my website which play videos and it has alot of ads. Can any one provide me a detail instructions how i can use this library to block ads on that iframe?

Thank You.

**Comment by remusao** [comment]
Hi @im-ashar,

I believe this issue and discussion is relevant: https://github.com/ghostery/adblocker/issues/3039

In particular the idea of using a service worker to block the ads.

Best,
