### ISSUE TITLE
Youtube TV (Leanback) ads not blocked

### ISSUE THREAD

**Issue by k2helix** [ghostery/adblocker#3462]
As the title says, I'm trying to block https://youtube.com/tv (using a PS4 or smart TV user agent) following the README example but ads still show up in any video or even when browsing. This does not happen in youtube default website so I don't know how to proceed and am looking for some advice. Thanks in advance.

**Comment by remusao** [comment]
Hey @k2helix,

Thanks for reaching out! Could you provide more details on how to reproduce the issue? Ideally with a minimum repro script which I can run to investigate. Are you using Puppeteer, Electron, Playwright or browser blocker?

**Comment by k2helix** [comment]
Hi, thanks for your response. You can see a whole electron app using it here: https://github.com/k2helix/YouTubeTV/blob/main/renderers/main/main.renderer.ts#L67 (its my fork to which I tried to add adblock). Hope this is what you were asking for.

**Comment by remusao** [comment]
Hi @k2helix,

There was a recent update in resources used by the adblocker to block ads on YouTube. Would you be able to check again if this brought an improvement on your end?

**Comment by k2helix** [comment]
Hi, I did it when it was released some days ago and also tried injecting the blocker earlier in the code but nothing worked. Note that sometimes (like 1 out of 5 times) when opening the app video ads don't get shown but they usually do so I try reopening it a few more times until I give up.

**Comment by remusao** [comment]
I did see some exception when trying it out locally, maybe some issue with latest resources. Cc @chrmod 

![image](https://github.com/ghostery/adblocker/assets/1299873/fa0c4f01-9e06-43bd-ae73-d82fe8e4db78)

**Comment by k2helix** [comment]
I see. Please let me know if there is anything I can do or you need me to do

**Comment by JellyBrick** [comment]
> I did see some exception when trying it out locally, maybe some issue with latest resources. Cc @chrmod
> 
> ![image](https://user-images.githubusercontent.com/1299873/273321578-fa0c4f01-9e06-43bd-ae73-d82fe8e4db78.png)

Additional information: Running YouTube Music with the `@cliqz/adblocker` enabled causes this error and disables the preload script.

https://github.com/th-ch/youtube-music/issues/1267

**Comment by remusao** [comment]
@JellyBrick @k2helix We've got a fix prepared here and locally I could get YouTube working again in Electron: https://github.com/ghostery/adblocker/pull/3501

**Comment by k2helix** [comment]
Hi again and thanks for working on a fix! I've been trying it on the project I mentioned above and it blocks ads. However, it seems that when playing a video, there's a black screen for ~20 secs which I think that means Youtube thinks it's showing ads.
Basically it's blocking ads but the video is not played until the time for the ads that were assigned ends (or that's what I believe).

**Comment by remusao** [comment]
@k2helix It seems like YouTube is pushing changes recently to circumvent blocking. I've checked with the latest assets just now and I cannot reproduce the issue anymore. Is it still happening to you?

**Comment by k2helix** [comment]
@remusao It seems to be working fine now. Ironical that Youtube makes changes to avoid blockers in the main website and it makes blockers work in the TV site. Thanks for your help!

**Comment by k2helix** [comment]
I have been using it for a bit and now when I opened the app and played a video the same thing (a black screen) happened.

**Comment by remusao** [comment]
Things are moving quickly and rules are updated every day. I've just merged the latest update. Hopefully that improves things but I think we should expect more instability with youtube.com in the coming days unfortunately.
