### ISSUE TITLE
[adblocker-electron] youtube.com not loading

### ISSUE THREAD

**Issue by AGNAB712** [ghostery/adblocker#3772]
Hello,
Recently (in the past day or 2) my app built with electron's webviews hasn't been able to load youtube anymore. Whenever I try to open youtube, it responds with a "did-fail-load" event and the devtools look like those attatched

![image_2024-02-10_192717336](https://github.com/ghostery/adblocker/assets/133778639/8950703d-e03b-4566-bdde-6e10377a6d56)
![image](https://github.com/ghostery/adblocker/assets/133778639/2e388fbf-9ccc-42e9-a3db-16105ad3e480)

I've looked around a little bit more and it seems it's just a problem with youtube, as other websites with ads on them still load fine and the ads get blocked.

**Comment by chrmod** [comment]
@AGNAB712 thank you for reporting. We should definitely investigate this closely.

Can you please share the complete text of the scriptlet that throws the syntax error? 

Could it be that you don't use the latest version of the ablocker engine? Can you please try to download the new one?

**Comment by AGNAB712** [comment]
Sure, I figured out that in order to replicate the bug, you don't need a webview.
Here is what I am using to recreate it.

```js
const { app, BrowserWindow } = require('electron')
const { ElectronBlocker } = require('@cliqz/adblocker-electron')

let mainWindow

function createWindow() {
	mainWindow = new BrowserWindow({
	 width: 800,
    	height: 600,
    	titleBarStyle: 'hidden'
    })

  mainWindow.loadURL('https://google.com')
  
  ElectronBlocker.fromPrebuiltAdsOnly(fetch).then((blocker) => {
    blocker.enableBlockingInSession(mainWindow.webContents.session);
  });
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  app.quit()
})
```

I double checked, I am using the latest version of the packages @cliqz/adblocker-electron (1.26.15) and electron (28.2.2).
I have also tried this with older versions of electron, and the issue is still prevalent. Thank you for taking the time to investigate this. Hopefully this is helpful

**Comment by chrmod** [comment]
@AGNAB712 we have a good progress on this one. The problem should go away Tomorrow when automatic assets update will be done.
