### ISSUE TITLE
Feature Request: Add manual entry to list

### ISSUE THREAD

**Issue by zirkelc** [ghostery/adblocker#3954]
Hi,

I hope I didn't overlook it, but is there a way to manually add entries to the Blocker, something like this:

```ts
const blocker = await PuppeteerBlocker.fromPrebuiltFull(fetch);

// add single entry
blocker.add('.cookie-monster');
// or multiple entries from a file
blocker.add(fs.readFileSync('./local-file').split('\n'));
```

I want to extend the prebuilt options with some custom rules, but the current API always needs a HTTP URL. That means I have host my list somewhere and the fetch it like this:

```ts
    const blocker = await PuppeteerBlocker.fromLists(
      fetch,
      [
        ...fullLists,
        'https://my-bucket.s3.eu-west-1.amazonaws.com/custom-list.txt',
      ]
    );
```

It would be nice if there were an easier option to add new entries. Happy to help out! 👍

**Comment by seia-soto** [comment]
Hi @zirkelc ,

We already support adding a filter entry to the engine directly. The `PuppeteerBlocker` instance is an extent of the `FiltersEngine`: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-puppeteer/adblocker.ts#L109 . Therefore, you can use `FiltersEngine.updateFromDiff`: https://github.com/ghostery/adblocker/blob/master/packages/adblocker/src/engine/engine.ts#L611

```ts
blocker.updateFromDiff({
  added: ['domain.tld##.cookie-monster']
})
```

I hope this answered your question. Thanks!

**Comment by zirkelc** [comment]
Awesome! Thank you for quick response!
