### ISSUE TITLE
Specifically accept/reject cookie popup keeping ads

### ISSUE THREAD

**Issue by teammakdi** [ghostery/adblocker#4128]
I'm looking to specifically just accept/reject cookie popups without disabling ads and trackers. There is no function exposed to do the same, there's `fromPrebuiltFull` but it disables ads and trackers as well.

I've created a demo script for the same.

```javascript
import puppeteer from 'puppeteer';
import {
    PuppeteerBlocker
} from '@cliqz/adblocker-puppeteer';
import fetch from 'cross-fetch';

const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.setViewport({
    width: 1080,
    height: 1024
});

await PuppeteerBlocker.fromLists(fetch, [
    "https://raw.githubusercontent.com/cliqz-oss/adblocker/master/packages/adblocker/assets/ublock-origin/annoyances.txt",
    "https://raw.githubusercontent.com/cliqz-oss/adblocker/master/packages/adblocker/assets/easylist/easylist-cookie.txt",
], {
    loadNetworkFilters: false
}).then((blocker) => {
    blocker.enableBlockingInPage(page);
});

await page.goto('https://www.rightmove.co.uk/');

await page.screenshot({
    path: 'screenshot.jpg'
});

await browser.close();
```

It works as expected by keeping ads and just blocking cookie popups.

Does the assets look enough to address cookie popups? 

I'm not sure if `ublock-origin/annoyances-others.txt` is to be included.

Possibly we can expose a function for the same.

Also by default it rejects the cookie popup, is there a functionality to accept the same?

**Comment by seia-soto** [comment]
Hi @teammakdi ,

To be clear, there's no functionality to accept or reject the cookie popup on the above lists. They tend to block the cookie popup by blocking the requests to CMPs (Consent Management Platform). Thus the role of those lists are to completely remove the interaction between the user and CMP. If you're looking for an automation script that actually takes an action to "reject" or "accept" the cookies, please check out the autoconsent project by duckduckgo.

I hope this made a progress on your question.

Thanks

**Comment by teammakdi** [comment]
Got it. Thanks.

**Comment by teammakdi** [comment]
<img width="822" alt="image" src="https://github.com/user-attachments/assets/14ab2887-ac02-4e20-9d85-9abb2dade555">

So just to confirm the ghostery web extension uses https://github.com/duckduckgo/autoconsent to reject the cookies.

Also any idea how could I access the domain info

<img width="359" alt="image" src="https://github.com/user-attachments/assets/86c44124-27e0-4814-b466-98791083bbef">

In puppeteer?

@seia-soto

**Comment by seia-soto** [comment]
Hi @teammakdi ,

First, Ghostery Browser Extension mixes multiple filter lists of blocking cookies not only autoconsent to provide the maximum coverage.

Second, this repository only represents the core functionality of the request matching and cosmetic data formation. Thus we don't have a full functionality of Ghostery Browser Extension in this repository. How you implement things depends on your goal not the library. Those domain information is provided by our another project: TrackerDB.

Best
