### ISSUE TITLE
Can you provide a link to the tracker list for Ghostery?

### ISSUE THREAD

**Issue by xiulou23** [ghostery/adblocker#4221]
I want to subscribe to Ghostery's tracker list with AdGuard Home, but after looking for a long time, I can't find a tracker list link.

**Comment by seia-soto** [comment]
Hi @xiulou23 ,

You can find out the data from TrackerDB's releases: https://github.com/ghostery/trackerdb/releases. However, our listing is not optimised for DNS use and we're not responsible for incorrect blocking in domain name level.

I hope you answered and have a great weekend.

Best,
HoJeong

**Comment by xiulou23** [comment]
> 您好 ，
> 
> 你可以从 TrackerDB 的 releases 中找到数据：https://github.com/ghostery/trackerdb/releases。但是，我们的列表并未针对 DNS 使用进行优化，因此我们不对域名级别的错误阻止负责。
> 
> 我希望您能回答并祝您周末愉快。
> 
> 最佳 HoJeong

thnak you
