### ISSUE TITLE
Customization for the Electron's webRequest module

### ISSUE THREAD

**Issue by sentialx** [ghostery/adblocker#811]
Currently, Electron does not support multiple webRequest handlers and it doesn't look like they want to move towards fixing this issue. Also, you don't provide a way to register these handlers manually. At this point, I need to declare the adblock engine as any and use its private methods like `onHeadersReceived` etc. I would propose a way to call `enableBlockingInSession` without registering the `webRequest` event listeners and the method would return some kind of callback processing the Electron details (if possible, detecting whether it's `onHeadersReceived` or `onBeforeRequest`) and returning the "action", so I could do for example:

```typescript
const { processDetails } = engine.enableBlockingInSession(session);
session.webRequest.onBeforeRequest((details, callback) => {
  ...
  callback({
    ...processDetails(details),
    ...myActions,
  )};
});

**Comment by remusao** [comment]
Hi @sentialx,

The situation with Electron is indeed far from ideal.  From your example, I think you could already do something like:

```js
session.webRequest.onBeforeRequest((details, callback) => {
  let response = {};
  engine.onBeforeRequest(details, (r) => { response = r; });

  callback({
    ..response,
    ...myActions,
  )};
});
```

The API is not perfect, but `onBeforeRequest`, `onHeadersReceived` , and `onGetCosmeticFilters` are all public methods of `ElectronBlocker`. Would this work for you?

**Comment by sentialx** [comment]
Yeah, it does work, but the code is ugly. I also need to inject the preloads by myself instead of just calling something like `engine.enableBlockingInSession({ networkFilters: false })`.

**Comment by remusao** [comment]
Hey @sentialx,

Really sorry for not being more active on this issue lately but I had a lot on my plate. I have been experimenting with different solutions to improve the situation and wanted to get your opinion about something (slightly different from what we discussed so far, but I think it has more potential to improve the API of the adblocker on different platforms and provide a nice abstraction for projects integrating the adblocker). The idea would be to create a "request pipeline" abstraction which would handle the listener to `webRequest` internally and allow to register multiple blocking listener. The pipeline could be either created externally and passed to the adblocker as an argument:

```typescript
import { RequestPipeline, ElectronBlocker } from '@cliqz/adblocker-electron';

// const pipeline = RequestPipeline.fromPuppeteerPage(page);
// const pipeline = RequestPipeline.fromPlaywrightPage(page);
const pipeline = RequestPipeline.fromElectronSession(session);
const cb = (request: Request, response: BlockingResponse): void  => {
  // Do something with `request`
  // response.cancel();
  // response.fulfill({ ... });
  // Or do nothing (i.e. just observe)
};

pipeline.register(cb);
// Register as many callbacks as you like
// pipeline.unregister(cb)

const blocker = ElectronBlocker.parse('...');
blocker.enableBlockingInSession(session, pipeline); // Give your own pipeline here
```

Or, let the `ElectronBlocker` create its own internally:
```typescript
const blocker = ElectronBlocker.parse('...');
const context = blocker.enableBlockingInSession(session);

// You can access pipeline and use it for your own things
context.pipeline.register((request) => {
  console.log(request.url);
});
```

Of course the API is just an idea and can be improved/fine-tuned. What would you think of something like that? The pipeline abstraction could also be used without the adblocker to allow registering multiple listeners easily in Electron/Puppeteer/Playwright/Browser extensions. I was thinking of publishing it as a separate package as well and shipping it with the adblocker package as well.

**Comment by sentialx** [comment]
It would work fine, only if the pipeline would allow me to register event listeners for all types of `webRequest` listeners and with `filters` support. For registering more listeners on `webRequest`, I'm using [`electron-better-web-request`](https://github.com/getstation/electron-better-web-request/blob/master/src/electron-better-web-request.ts) which has everything I need for implementing my own Chrome extension API in Electron.

The problem with your library is that it automatically manages registering and unregistering `onBeforeRequest` event, without returning any info, needed for me to manually clean up the listeners. In this case, `electron-better-web-request` returns the id of a registered `webRequest` listener, which then I can use for removing the listener. I made a workaround here:

https://github.com/wexond/desktop/blob/2d2d9a3cde91851275953ac8b49cc57c6a3a5913/src/main/services/adblock.ts#L63-L136

**Comment by remusao** [comment]
Thanks a lot for your feedback @sentialx, this makes a lot of sense. I knew there was a library doing something like that for Electron but I could not find the name anymore! I am trying to find ways to abstract away differences between platforms (e.g. Electron/Puppeteer/Browser/Playwright) to reduce the maintenance cost, and I think a generic request pipeline which works on all the platforms would make sense. I will try putting a prototype together in the week-end.

**Comment by sentialx** [comment]
The library only accepts only an id, I think.

**Comment by remusao** [comment]
Closing this as unfortunately I did not have bandwidth to work on this and will likely not be able to in the foreseeable future. If anyone from the community would like to pick this up I'd be happy to brainstorm and review a pull request to move the ball forward.
