### ISSUE TITLE
[Question] Why isn't node-fetch/cross-fetch a dependency ?

### ISSUE THREAD

**Issue by KaKi87** [ghostery/adblocker#832]
Hello,

Why projects using this one as dependency must also install a `fetch` polyfill themselves instead of having it declared as a dependency in [package.json](https://github.com/cliqz-oss/adblocker/blob/master/package.json) ?

Thanks

**Comment by remusao** [comment]
Hi @KaKi87,

Thanks for reaching out. The initial reason is that there are many choices to polyfill fetch and some project already dependent on one of them (e.g. `cross-fetch` or `node-fetch` or `isometric-fetch` or ...), others imitate the `fetch` API using libraries such as `got` or `axios`. Picking one would impose a duplicated dependency on them. On the other hand it's true that the overhead is probably fairly small so maybe would it make sense to reconsider this decision, for convenience.

**Comment by KaKi87** [comment]
Well, I think the project should choose it's dependency on its own instead of asking the developer to make a choice, besides, I always use `axios` so I'm not interesting in installing a `fetch` polyfill, but your project is forcing me have one in my own `package.json` while I didn't asked for it.
Thanks

**Comment by remusao** [comment]
Makes sense, I will think a bit more about it. May I ask which package you are using in particular? `@cliqz/adblocker-electron` or `@cliqz/adblocker-puppeteer`?

**Comment by KaKi87** [comment]
The one for Puppeteer.
It's life-saving by the way, thank you very much.
After I discovered I couldn't use uBlock in headless mode, I tried to use HTTP request interception and `ad-block-js` and it failed some rules from EasyList, I was hopeless and almost ready to start making a whitelist array, which would have required a very (easy, but) long, long time to create 😅

**Comment by remusao** [comment]
@KaKi87 a quick update. I could not spend much time on the project lately but I am thinking about ways to make the APIs easier to use and will try to push that forward soon. In the meanwhile, maybe you could have a look at [`puppeteer-extra`](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-adblocker#usage) which bundles the adblocker and has a more high-level API.

**Comment by remusao** [comment]
Given this issue is solved by `puppeteer-extra`, which I believe is a nice higher-level API to include the adblocker in a Puppeteer project, and that I am not able to make such changes at this point I will close this issue. If anyone from the community is willing to make a proposal on how to improve the API I'd be happy to review.
